config/routes.rb
Rails.application.routes.draw do
  root 'static_pages#home'
  get 'users/sign_up' => 'users#new'
  post 'users/sign_up' => 'users#create'
  get 'users/sign_in' => 'sessions#new'
  post 'users/sign_in' => 'sessions#create'
  delete 'logout' => 'sessions#destroy'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
# frozen_string_literal: true

class User < ApplicationRecord
  attr_accessor :remember_token
  has_secure_password

  def self.digest(string)
    cost = ActiveModel::SecurePassword.min_cost ?
                       BCrypt::Engine::MIN_COST :
                       BCrypt::Engine.cost
    BCrypt::Password.create(string, cost: cost)
  end

  def self.new_token
    SecureRandom.urlsafe_base64
  end

  def remember
    self.remember_token = User.new_token
    update_attribute(:remember_digest, User.digest(remember_token))
  end

  def authenticated?(remember_token)
    return false if remember_digest.nil?
    BCrypt::Password.new(remember_digest).is_password?(remember_token)
  end

  def forget
    update_attribute(:remember_digest, nil)
  end
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  include SessionsHelper
end

app/controllers/sessions_controller.rb
# frozen_string_literal: true

# Description/Explanation of SessionsController class

class SessionsController < ApplicationController
  def new; end

  def create
    user = User.find_by email: params[:session][:email].downcase
    if user&.authenticate(params[:session][:password])
      flash[:success] = 'Successfully login'
      sign_in user
      params[:session][:remember_me] == '1' ? remember(user) : forget(user)
      redirect_to root_path
    else
      flash.now[:danger] = 'In Invalid email/password combination'
      render :new
    end
  end

  def destroy
    logout if signed_in?
    flash[:success] = "You are logged out"
    redirect_to users_sign_in_path
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home; end
end

app/controllers/users_controller.rb
# frozen_string_literal: true

# Description/Explanation of UsersController class

class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.new user_params
    if @user.save
      sign_in @user
      remember @user
      flash[:success] = 'Successfully register'
      redirect_to root_path
    else
      flash.now[:alert] = 'Register failed'
      render :new
    end
  end

  private
    def user_params
      params.require(:user).permit :email, :password, :password_confirmation
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sessions_helper.rb
# frozen_string_literal: true

# Description/Explanation of SessionsHelper module

module SessionsHelper
  def sign_in(user)
    session[:user_id] = user.id
  end

  def current_user?(user)
    user == current_user
  end

  def signed_in?
    !current_user.nil?
  end

  def logout
    forget(current_user)
    session.delete(:user_id)
    @current_user = nil
  end

  def remember(user)
    user.remember
    cookies.permanent.signed[:user_id] = user.id
    cookies.permanent[:remember_token] = user.remember_token
  end

  def current_user
    if (user_id = session[:user_id])
      @current_user ||= User.find(user_id)
    elsif (user_id = cookies.signed[:user_id])
      user = User.find(user_id)
      if user&.authenticated?(cookies[:remember_token])
        sign_in user
        @current_user = user
      end
    end
  end

  def forget(user)
    user.forget
    cookies.delete(:user_id)
    cookies.delete(:remember_token)
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Shop</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

    <link href="https://fonts.googleapis.com/css2?family=Mystery+Quest&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
    <script src="https://kit.fontawesome.com/4365b682ab.js" crossorigin="anonymous"></script>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js"></script>
  </head>

  <body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarTogglerDemo02" aria-controls="navbarTogglerDemo02" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarTogglerDemo02">
        <ul class="navbar-nav float-left mr-auto ml-3 pl-1" style="color:'black'">
          <li class="nav-item active nav-link">
            <h1 style="font-family: 'Mystery Quest', cursive;"><%= link_to 'E-Shop', root_path %></h1>
          </li>
        </ul>

        <ul class="navbar-nav float-right">
          <% if signed_in? %>
            <li class="nav-item d-none d-md-block">
              <a class="nav-link" href="javascript:void(0)">
                <form class="form-inline my-2 my-lg-0">
                  <input class="form-control mr-sm-2" type="search" placeholder="Search">
                  <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
                </form>
              </a>
            </li>
            <li class="nav-item dropdown">
              <a class="nav-link dropdown-toggle" href="javascript:void(0)" data-toggle="dropdown"
                  aria-haspopup="true" aria-expanded="false">
                <span class="ml-2 d-none d-lg-inline-block">
                  <span class="text-dark"><%= current_user.email %></span>
                  <i data-feather="chevron-down" class="svg-icon"></i>
                </span>
              </a>

              <div class="dropdown-menu dropdown-menu-right user-dd animated flipInY">
                <div class="dropdown-item nav-item nav-link">
                  <%= link_to "Logout", logout_path, method: :delete,
                                                  data: { confirm: 'Are you sure?' },
                                                  class: 'btn btn-rounded' %>
                </div>
              </div>
            </li>
          <% else %>
            <li class="nav-item nav-link">
              <%= link_to 'Sign up', users_sign_up_path, class:"btn btn-primary" %>
            </li>

            <li class="nav-item nav-link">
              <%= link_to 'Sign in', users_sign_in_path, class:"btn btn-primary" %>
            </li>

            <li class="nav-item d-none d-md-block">
              <a class="nav-link" href="javascript:void(0)">
                <form class="form-inline my-2 my-lg-0">
                  <input class="form-control mr-sm-2" type="search" placeholder="Search">
                  <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
                </form>
              </a>
            </li>
          <% end %>
        </ul>
      </div>
    </nav>
    <%= render 'shared/flashregister'%>
    <%= yield %>
  </body>
</html>

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      The form contains <%= pluralize(object.errors.count, "error") %>.
    </div>
    <ul>
      <% object.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_flashregister.html.erb
<center>
 <div class="flash">
   <% flash.each do |key, value| %>
     <div class="alert alert-<%= key %> alert-dismissible fade show">
       <button type="button" class="close" data-dismiss="alert">&times;</button>
       <h4 class="text-left"><%= value %></h4>
     </div>
   <% end %>
 </div>
</center>

app/views/static_pages/home.html.erb
<h1>Welcome</h1>

app/views/users/new.html.erb
<div class="container">
 <div class="row">
   <div class="col-lg-offset-3 col-lg-6">
     <h1 class="text-center">Sign up</h1>
     <%= form_for :user, url: users_sign_up_path do |f| %>
       <%= render 'shared/error_messages', object: @user %>

       <div class="form-group">
         <%= f.label :email %>
         <%= f.email_field :email, placeholder: "Enter your email", class: "form-control" %>
       </div>

       <div class="form-group">
         <%= f.label :password %>
         <%= f.password_field :password, placeholder: "Enter your password", class: "form-control" %>
       </div>

       <div class="form-group">
         <%= f.label :password_confirmation%>
         <%= f.password_field :password_confirmation, placeholder: "Retype your password", class: "form-control" %>
       </div>

       <div class="text-center">
         <%= f.submit "Sign up", class: "btn btn-info col-lg-12" %>
       </div>
     <% end %>
   </div>
 </div>
</div>